# Generated by Django 5.2.7 on 2025-11-05 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0006_rename_creado_en_pedido_fecha_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetallePedido',
        ),
    ]
