# Generated by Django 5.2.7 on 2025-11-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0008_producto_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
